version: '3'
services:
  python:
    build: .
    environment:
      PORT: ${PORT}
      # GOOGLE_APPLICATION_CREDENTIALS: ${GOOGLE_APPLICATION_CREDENTIALS}
      FCM_KEY: ${FCM_KEY}
    ports:
      - "80:${PORT}"
    volumes:
      - ./app:/app
      - ./service_account:/tmp/keys:ro
